### ISSUE TITLE
Bug report batch: PR 73

### ISSUE THREAD

**Issue by blairmunroakusa** [interlock-network/threatslayer#75] opened 2023-09-09 12:14 UTC
Per checking functionality for PR [https://github.com/interlock-network/threatslayer/pull/73](https://github.com/interlock-network/threatslayer/pull/73)

This list is what I found broken with `dan/remove-seed-phrase` sans PR 73 merge. PR 73 fixes the weird lingering CSS artifacts on banner close (see crossed out text).

#### `Update Address` functionality:
- ss58 validation not present or broken
- When attempting to break valid address, result in `Uncaught ReferenceError: $i18n is not defined`
- When attempting to submit, 404 return
#### `Forgot Password` functionality:
- On email submit, 422 return
#### When clicking on extension icon:
- Apparent success, but `Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.`
#### ~When closing banner:~
- ~On some websites, closing banner has significant impact on original styling.~
- ~Example: (https://polkadot.js.org/docs/util-crypto/examples/verify-signature/)[https://polkadot.js.org/docs/util-crypto/examples/verify-signature/] --closing banner forces background into 'dark-mode' vibe.~
- ~Example: github font boldness is uniformly reduced.~
[This is fixed by PR73.](https://github.com/interlock-network/threatslayer/pull/73)
#### Allowlist Site red X:
- Undefined response on click -- `ReferenceError: response is not defined`   ....prolly not a bug
- oh wait...operation succeeds in UI, but 404 backend for site-forget
#### Credential collision:
- Registration attempt with same credentials returns 409, w no alert nor specification of what collides.
#### URL process error:
- After button fuzz mashing between banner tests and dashboard abuse, TS loses ability to pass valid URLs. I cannot figure out how to reproduce with my little html knowledge, the error: `Error processing URL: SyntaxError: Unexpected token '<', "<!doctype "... is not valid JSON`, coming from `service/worker.js`, caught gracefully from within `scanUrl` block in listener.

**Comment by DecentralizedDan** [comment] 2023-10-03 23:52
The remaining issues here are due to incomplete GALACTUS endpoints -- I'm closing until they are reproduced on the latest commit.

**Closed by DecentralizedDan** 2023-10-03 23:52 UTC
